---
- name: Update Files inside VM
  hosts: all
  become: true

  tasks:
    # Update apt repository and cache
    - name: Update apt repository and cache
      apt:
        update_cache: yes

    # Verify Docker installation
    - name: Verify Docker installation
      shell: docker --version
      register: docker_version
      ignore_errors: yes
      args:
        executable: /bin/bash

    # Print Docker version
    - name: Docker version
      debug:
        msg: "Docker installed successfully: {{ docker_version.stdout }}"
        
    # Copying main_app.py into the VM
    - name: Copy main.py from repo to ec2
      ansible.builtin.copy:
        src: ../WorkingDir/main.py
        dest: /home/ubuntu/api_app/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

      # Copying the Dockerfile into the vm
    - name: Copy Dockerfile from repo to ec2
      ansible.builtin.copy:
        src: ../WorkingDir/Dockerfile
        dest: /home/ubuntu/api_app/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

      # Copying requirements.txt into the vm
    - name: Copy requirements.txt from repo to ec2
      ansible.builtin.copy:
        src: ../WorkingDir/requirements.txt
        dest: /home/ubuntu/api_app/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
