name: Setup Docker on the VM with Ansible

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Choose Environment
                options:
                    - dev
                default: dev
jobs:
    install-docker:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./Ansible
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download instance IP artifact
              uses: actions/download-artifact@v4
              with:
                name: instance-ip
                path: ./Ansible


            - name: Read instance IP from file
              run: echo "INSTANCE_IP=$(cat ./Ansible/instance_ip.txt)" >> $GITHUB_ENV

            - name: Create SSH directory
              run: mkdir -p ~/.ssh

            - name: Add host to known_hosts
              run: ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts

            - name: Check and Install Ansible
              run: |
                if ! command -v ansible &> /dev/null; then
                  echo "Ansible not found. Installing..."
                  sudo apt-get update && sudo apt-get install -y ansible
                else
                  echo "Ansible is already installed."
                fi

            - name: Ensure everything is up to date
              run: |
                sudo dpkg --configure -a
                sudo apt-get update --fix-missing
                sudo apt-get -f install 

            - name: Setup SSH key for connection to AWS VM
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.AWS_SSH_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Run ansible playbook to install Docker
              run: ansible-playbook -u ubuntu -i $INSTANCE_IP, --private-key ~/.ssh/id_rsa Docker.yaml
