name: Health Check

on:
  workflow_dispatch:  # Allows manual triggering with inputs
    inputs:
      UserInput:
        description: 'Choose deployment type'
        required: true
        default: 'skip-wait'  # Default value (can be overridden)
        type: choice
        options:
          - skip-wait

  workflow_run:
    workflows: ["Upload Files"]  # Runs after "Upload Files" workflow
    types:
      - completed

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read EC2 IP Address
        id: read_ip
        run: |
          IP=$(cat terraform/ip_cache/ec2_ip.txt)
          echo "IP=$IP" >> $GITHUB_OUTPUT

      - name: Set IP as Environment Variable
        run: |
          echo "EC2_IP=${{ steps.read_ip.outputs.IP }}" >> $GITHUB_ENV

      - name: Wait for Deployment (if triggered automatically)
        if: ${{ github.event.inputs.UserInput != 'skip-wait' }}  # Only wait if UserInput is not 'skip-wait'
        run: sleep 300 

      - name: Check Website Health
        run: |
          # Disable immediate exit to capture curl's exit code
          set +e
          CLEAN_IP=$(echo "${{ env.EC2_IP }}" | tr -d '[:space:]' | tr -d ')')
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://$CLEAN_IP)
          CURL_EXIT_CODE=$?
          # Re-enable immediate exit
          set -e
      
          # Check if curl failed due to network issues (exit code 7)
          if [[ $CURL_EXIT_CODE -eq 7 ]]; then
            echo "Website was not found (curl exit code 7)"
            exit 1
          fi
      
          # Check if the HTTP response code is 200 (OK)
          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Health check failed! HTTP Status: $RESPONSE"
            exit 1
          fi

      - name: Confirm Success
        run: echo "Health check passed successfully!"
