name: Upload files

on:
    workflow_dispatch:
        inputs:
            ip:
                type: string
                description: Enter the IP
                default: SlaptasIPAdresas
jobs:

    Update-Files:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./Ansible
        steps:
        #Checkout code so that the palybook is accessible
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Create SSH directory
              run: mkdir -p ~/.ssh

            - name: Restore EC2 IP Address
              uses: actions/cache@v3
              with:
                path: terraform/ip_cache
                key: ec2-ip-address
                restore-keys: ec2-ip-address

            - name: Show Cached IP Address
              run: cat ip_cache/ec2_ip.txt

            - name: Add host to known_hosts
              run: ssh-keyscan -H ${{ github.event.inputs.ip }} >> ~/.ssh/known_hosts

            - name: Setup SSH key for connection to AWS VM
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.AWS_SSH_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Run ansible playbook to upload the code
              run: ansible-playbook -u ubuntu -i ${{ github.event.inputs.ip }}, --private-key ~/.ssh/id_rsa Upload.yaml
